
function read_controller_config(this_block)

  % Revision History:
  %
  %   03-Apr-2020  (14:01 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     /home/seba/Workspace/projects/DRAM_ring_buffer/fsm_test/read_controller.v
  %
  %

  this_block.setTopLevelLanguage('Verilog');

  this_block.setEntityName('read_controller');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  %this_block.tagAsCombinational;

  this_block.addSimulinkInport('bram_full');
  this_block.addSimulinkInport('rd_val');
  this_block.addSimulinkInport('en');
  this_block.addSimulinkInport('rst');
  this_block.addSimulinkInport('dram_val');

  this_block.addSimulinkOutport('dram_addr');
  this_block.addSimulinkOutport('en_read');
  this_block.addSimulinkOutport('write_bram');
  this_block.addSimulinkOutport('state');
  this_block.addSimulinkOutport('counter');

  dram_addr_port = this_block.port('dram_addr');
  dram_addr_port.setType('UFix_24_0');
  en_read_port = this_block.port('en_read');
  en_read_port.setType('UFix_1_0');
  en_read_port.useHDLVector(false);
  write_bram_port = this_block.port('write_bram');
  write_bram_port.setType('UFix_1_0');
  write_bram_port.useHDLVector(false);
  state_port = this_block.port('state');
  state_port.setType('UFix_4_0');
  counter_port = this_block.port('counter');
  counter_port.setType('UFix_8_0');

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('bram_full').width ~= 1);
      this_block.setError('Input data type for port "bram_full" must have width=1.');
    end

    this_block.port('bram_full').useHDLVector(false);

    if (this_block.port('rd_val').width ~= 1);
      this_block.setError('Input data type for port "rd_val" must have width=1.');
    end

    this_block.port('rd_val').useHDLVector(false);

    if (this_block.port('en').width ~= 1);
      this_block.setError('Input data type for port "en" must have width=1.');
    end

    this_block.port('en').useHDLVector(false);

    if (this_block.port('rst').width ~= 1);
      this_block.setError('Input data type for port "rst" must have width=1.');
    end

    this_block.port('rst').useHDLVector(false);

    if (this_block.port('dram_val').width ~= 24);
      this_block.setError('Input data type for port "dram_val" must have width=24.');
    end

  end  % if(inputTypesKnown)
  % -----------------------------

  % -----------------------------
   if (this_block.inputRatesKnown)
     setup_as_single_rate(this_block,'clk','ce')
   end  % if(inputRatesKnown)
  % -----------------------------

    % (!) Set the inout port rate to be the same as the first input 
    %     rate. Change the following code if this is untrue.
    uniqueInputRates = unique(this_block.getInputRates);

  % (!) Custimize the following generic settings as appropriate. If any settings depend
  %      on input types, make the settings in the "inputTypesKnown" code block.
  %      The addGeneric function takes  3 parameters, generic name, type and constant value.
  %      Supported types are boolean, real, integer and string.
  this_block.addGeneric('a','integer','0');
  this_block.addGeneric('b','integer','1');
  this_block.addGeneric('c','integer','2');
  this_block.addGeneric('d','integer','3');
  this_block.addGeneric('e','integer','4');
  this_block.addGeneric('f','integer','5');
  this_block.addGeneric('g','integer','6');
  this_block.addGeneric('h','integer','7');
  this_block.addGeneric('i','integer','8');
  this_block.addGeneric('j','integer','9');
  this_block.addGeneric('k','integer','10');
  this_block.addGeneric('l','integer','11');
  this_block.addGeneric('m','integer','12');

  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('read_controller.v');

return;


% ------------------------------------------------------------

function setup_as_single_rate(block,clkname,cename) 
  inputRates = block.inputRates; 
  uniqueInputRates = unique(inputRates); 
  if (length(uniqueInputRates)==1 & uniqueInputRates(1)==Inf) 
    block.addError('The inputs to this block cannot all be constant.'); 
    return; 
  end 
  if (uniqueInputRates(end) == Inf) 
     hasConstantInput = true; 
     uniqueInputRates = uniqueInputRates(1:end-1); 
  end 
  if (length(uniqueInputRates) ~= 1) 
    block.addError('The inputs to this block must run at a single rate.'); 
    return; 
  end 
  theInputRate = uniqueInputRates(1); 
  for i = 1:block.numSimulinkOutports 
     block.outport(i).setRate(theInputRate); 
  end 
  block.addClkCEPair(clkname,cename,theInputRate); 
  return; 

% ------------------------------------------------------------

